### PR TITLE
add sNBT IO

### PR DESCRIPTION
**Pull request by ExaInsanity**
This PR implements read/write operations for sNBT - stringified NBT.

This also requires #11 be merged to avoid merge conflicts

### CODE REVIEW

**Comment by ExaInsanity** [comment]
that commit was meant to read "add snbt writer"

**Comment by ExaInsanity** [comment]
@Zefyro the PR is now ready for review. Keep in mind that merging this requires #11 to be merged first, as it lays some groundwork for this PR

**Review by Zefyro — APPROVED** [review]
First thoughts: *Its readable*

**Comment by ExaInsanity** [comment]
if you consider it mergeable, remember to merge #11 first

**Pull request merged**
